name: ci

on:
  pull_request:
  push:
    branches: ['**']

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    # All run steps below execute from dan-app/
    defaults:
      run:
        working-directory: dan-app

    steps:
      - uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Use Node 20 (cache pnpm)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint --if-present

      - name: Test
        run: pnpm test --if-present -- --ci

      - name: Build (sanity)
        run: pnpm run build