name: ci

on:
  pull_request:
  push:
    branches: ['**']

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install pnpm first
      - uses: pnpm/action-setup@v4
        with:
          version: 10.12.1
          run_install: false

      # Then set up Node and enable pnpm cache
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm test --if-present -- --ci

      - name: Build (sanity)
        run: pnpm run build