name: ci

on:
  pull_request:
  push:
    branches: ['**']

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm run lint --if-present

      - name: Test
        run: pnpm test --if-present -- --ci

      - name: Build (sanity)
        run: pnpm run build